[custom.all.typesafe-tensors]
type = "local"
path = ""
ipkg = "typesafe-tensors.ipkg"

[custom.all.typesafe-tensors-examples]
type = "local"
path = "examples"
ipkg = "typesafe-tensors-examples.ipkg"

[custom.all.typesafe-tensors-tests]
type = "local"
path = "tests"
ipkg = "typesafe-tensors-tests.ipkg"

[custom.all.elab-util]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "ffbfe4f50900f45722035a16e6285f580047e846"
ipkg   = "elab-util.ipkg"